FROM hfdresearch/swak4foamandpyfoam:latest-v6.0

ENV USER=openfoam USER_ID=98765 USER_GID=98765

USER root

RUN apt-get -y update && \
    apt-get install -y \
        gcc \
        cmake \
        g++ \
        gfortran \
        libopenblas-dev \
        git \
        sudo && \
    echo "openfoam:openfoam" | chpasswd && \
    adduser openfoam sudo

#  Get & Compile Elmer
RUN cd /opt && \
    git clone https://github.com/ElmerCSC/elmerfem.git && \
    cd elmerfem && \
    git checkout release && \
    git log --pretty=oneline | tail -n 10 | tee build.log && \
    mkdir build && \
    cd build && \
    cmake -DWITH_MPI=TRUE -DCMAKE_BUILD_TYPE=Release ../ | tee build.log && \
    make -j install | tee build.log

# Add EOF-Library
ADD ./ EOF-Library

# Update environment & install script for dynamic UID:GID mapping
RUN echo ". /home/openfoam/EOF-Library/etc/bashrc" >> .bashrc && \
    mv /home/openfoam/EOF-Library/docker/user-mapping.sh / && \
    chmod u+x /user-mapping.sh

ENTRYPOINT ["/user-mapping.sh"]
