FROM openfoam/openfoam6-paraview54:latest

USER root
RUN apt-get -y update && \
    apt-get install -y \
        gcc \
        cmake \
        g++ \
        gfortran \
        libopenblas-dev \
        git \
        valgrind

# Debuggers do not like OpenMPI from Ubuntu repo, compile from scratch
RUN wget https://download.open-mpi.org/release/open-mpi/v1.10/openmpi-1.10.2.tar.gz && \
    tar xvzf openmpi-1.10.2.tar.gz && \
    rm openmpi-1.10.2.tar.gz && \
    cd openmpi-1.10.2 && \
    ./configure --prefix=$(pwd)/install && \
    make -j install

# Writting stuff to .bashrc
RUN echo "\n# OpenMPI for debugging" >> .bashrc && \
    echo "export MPI_INST=/home/openfoam/openmpi-1.10.2/install" >> .bashrc && \
    echo "export PATH=\$MPI_INST/bin:\$MPI_INST/include:\$PATH" >> .bashrc && \
    echo "export LD_LIBRARY_PATH=\$MPI_INST/lib:\$LD_LIBRARY_PATH" >> .bashrc

#  Elmer
RUN git clone https://github.com/ElmerCSC/elmerfem.git
RUN chown -R openfoam:openfoam elmerfem

# Compile Elmer
RUN cd elmerfem && \
    mkdir build && \
    cd build && \
    cmake -DWITH_MPI=TRUE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_Fortran_FLAGS_DEBUG="-cpp -g -O0 -fbacktrace -fcheck=all -Wall -Wtabs -Wuninitialized -Wextra -Wconversion -ffpe-trap=overflow -ffree-line-length-none" ../ && \
    make -j install

# Writting stuff to .bashrc
RUN echo "\n# Lines from docker/Dockerfile-build" >> .bashrc && \
    echo "## OpenFOAM" >> .bashrc && \
    echo "source /opt/openfoam6/etc/bashrc" >> .bashrc && \
    echo "\n## Elmer FEM" >> .bashrc && \
    echo "export ELMER_SRC=\$HOME/elmerfem" >> .bashrc && \
    echo "export ELMER_BUILD=\$ELMER_SRC/build" >> .bashrc && \
    echo "alias elmerUpdate='git -C \$ELMER_SRC pull; make install -C \$ELMER_BUILD'" >> .bashrc && \
    echo "\n## EOF-Library" >> .bashrc && \
    echo "source \$HOME/EOF-Library/etc/bashrc" >> .bashrc    echo "\n## Debugging" >> .bashrc && \
    echo "export WM_COMPILE_OPTION=Debug" >> .bashrc && \
    echo "export PATH=/home/openfoam/debugger/bin:\$PATH" >> .bashrc

# EOF-Library
RUN git clone https://github.com/jvencels/EOF-Library.git
RUN chown -R openfoam:openfoam EOF-Library
