FROM openfoam/openfoam5-paraview54

USER root
RUN apt-get -y update && \
    apt-get install -y \
        gcc \
        cmake \
        g++ \
        gfortran \
        libopenblas-dev \
        git

#  Elmer
RUN git clone https://github.com/ElmerCSC/elmerfem.git

# EOF-Library
ADD ./ EOF-Library
RUN chown -R openfoam:openfoam EOF-Library

# Copy tests
RUN cd EOF-Library/tests && \
    for dir in *; do [ -d "$dir" ] && cp ../libs/OpenFOAM2Elmer/*.F90 "$dir" ; done && \
    for dir in *; do [ -d "$dir" ] && cp ../libs/Elmer2OpenFOAM/*.F90 "$dir" ; done && \
    for dir in *; do [ -d "$dir" ] && cp -r "$dir" ~/elmerfem/fem/tests ; done

# Compile Elmer
RUN cd ~/elmerfem && \
    mkdir build && \
    cd build && \
    cmake -DWITH_MPI=TRUE -C ../ci/precaches/opts-ubuntu-xenial.cmake ../ && \
    make -j$(nproc) install

RUN chown -R openfoam elmerfem

# Compile EOF-Library OF part
RUN EOF-Library/docker/compile.sh -v 5.0-dev -f $HOME/EOF-Library
