FROM hfdresearch/swak4foamandpyfoam:latest-v6.0

USER root
RUN apt-get -y update && \
    apt-get install -y \
        gcc \
        cmake \
        g++ \
        gfortran \
        libopenblas-dev \
        git

#  Elmer
RUN git clone https://github.com/ElmerCSC/elmerfem.git
RUN chown -R openfoam:openfoam elmerfem

# Compile Elmer
RUN cd elmerfem && \
    mkdir build && \
    cd build && \
    cmake -DWITH_MPI=TRUE -DCMAKE_BUILD_TYPE=Release ../ && \
    make -j install

# Writting stuff to .bashrc
RUN echo "\n# Lines from docker/Dockerfile-build" >> .bashrc && \
    echo "## OpenFOAM" >> .bashrc && \
    echo "source /opt/openfoam6/etc/bashrc" >> .bashrc && \
    echo "\n## Elmer FEM" >> .bashrc && \
    echo "export ELMER_SRC=\$HOME/elmerfem" >> .bashrc && \
    echo "export ELMER_BUILD=\$ELMER_SRC/build" >> .bashrc && \
    echo "alias elmerUpdate='git -C \$ELMER_SRC pull; make install -C \$ELMER_BUILD'" >> .bashrc && \
    echo "\n## EOF-Library" >> .bashrc && \
    echo "source \$HOME/EOF-Library/etc/bashrc" >> .bashrc

# EOF-Library
RUN git clone https://github.com/jvencels/EOF-Library.git
RUN chown -R openfoam:openfoam EOF-Library

ENTRYPOINT /bin/bash -c /entry.sh
